# Generated by Django 4.0.5 on 2022-06-01 19:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_tutorial_tutorial_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 1, 16, 10, 43, 627199), verbose_name='date published'),
        ),
    ]
