# Generated by Django 4.0.5 on 2022-06-10 17:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_tutorialcategory_tutorial_tutorial_sluh_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorial',
            old_name='tutorial_sluh',
            new_name='tutorial_slug',
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 10, 14, 15, 37, 757816), verbose_name='date published'),
        ),
    ]
