# Generated by Django 4.0.5 on 2022-06-10 17:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_tutorial_sluh_tutorial_tutorial_slug_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorialcategory',
            old_name='category_sumaery',
            new_name='category_summary',
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 10, 14, 17, 16, 705725), verbose_name='date published'),
        ),
    ]
