# Generated by Django 4.0.5 on 2022-06-10 17:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rename_category_sumaery_tutorialcategory_category_summary_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tutorialseries',
            options={'verbose_name_plural': 'Series'},
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 10, 14, 19, 12, 57678), verbose_name='date published'),
        ),
    ]
